[build]
# Increase stack size for Windows builds to support deep recursion
# This sets the stack size at link time
rustflags = ["-C", "link-args=-Wl,-zstack-size=268435456"]

[target.x86_64-pc-windows-msvc]
# For Windows MSVC: Set stack size to 256MB (268435456 bytes)
rustflags = ["-C", "link-args=/STACK:268435456"]

[target.x86_64-pc-windows-gnu]
# For Windows GNU: Set stack size to 256MB
rustflags = ["-Wl,--stack,268435456"]
